name: Deploy mdBook

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >> ~/.ssh/config << EOF
          Host venn
            HostName wiki.venn.dev
            User root
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Install mdbook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz
          tar -xzvf mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz

      - name: Build site
        run: ./mdbook build

      - name: Cleanup old files
        run: |
          ssh venn "rm -r /var/www/wiki.venn.dev/"
          ssh venn "mkdir -p /var/www/wiki.venn.dev/html"

      - name: Install requirements
        run: rsync -rsP ./book/ root@wiki.venn.dev:/var/www/wiki.venn.dev/html

      - name: Reload nginx
        run: ssh venn "systemctl reload nginx"
